#!/usr/bin/env python
#################################################################################
# Copyright 2018 ROBOTIS CO., LTD.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#################################################################################

# Authors: Gilbert #

import rospy
import math
from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist
import time  # time module
import smbus  # led sensor
from nav_msgs.msg import Odometry  # odom

LINEAR_VEL = 0.22
STOP_DISTANCE = 0.45
LIDAR_ERROR = 0.05
ANGLE = 90
SAFE_STOP_DISTANCE = STOP_DISTANCE + LIDAR_ERROR


# odom global variables
SUM = 0
COUNT = 0

# odom subscriber callback


def odometryCallback(data):
    # retrieve velocity here
    # COUNT = COUNT + 1
    # SUM = SUM + data.twist.twist.linear.x
    # average_linear_speed = SUM/COUNT
    #rospy.loginfo('velocity : %f', data.twist.twist.linear.x)
    pass


class Obstacle():

    def __init__(self):
        self._cmd_pub = rospy.Publisher('cmd_vel', Twist, queue_size=1)
        self.obstacle()

    def get_scan(self):
        scan = rospy.wait_for_message('scan', LaserScan)
        scan_filter = []

        samples = len(scan.ranges)  # The number of samples is defined in
        # turtlebot3_<model>.gazebo.xacro file,
        # the default is 360.

        samples_view = ANGLE        # 1 <= samples_view <= samples

        if samples_view > samples:
            samples_view = samples

        if samples_view is 1:
            scan_filter.append(scan.ranges[0])

        else:
            left_lidar_samples_ranges = -(samples_view//2 + samples_view % 2)
            right_lidar_samples_ranges = samples_view//2

            left_lidar_samples = scan.ranges[left_lidar_samples_ranges:]
            right_lidar_samples = scan.ranges[:right_lidar_samples_ranges]
            scan_filter.extend(left_lidar_samples + right_lidar_samples)

        for i in range(samples_view):
            # set value to 3.5 in case of a faulty reading and hope we don't get all 0 readings
            if scan_filter[i] == float('Inf'):
                scan_filter[i] = 3.5
            elif math.isnan(scan_filter[i]):
                scan_filter[i] = 3.5
            elif scan_filter[i] == 0:
                scan_filter[i] = 3.5

        return scan_filter

    def obstacle(self):
        twist = Twist()
        turtlebot_moving = True
        t_end = time.time() + 120  # time_time returns time since 1st jan 1970
        speed_updates = 0  # for average speed
        speed_accumulation = 0  # for average speed
        collision_count = 0  # collision counter
        red_count = 0
        full_stop_turn_count = 0

        # LED
        # Get I2C bus
        bus = smbus.SMBus(1)

        # ISL29125 address, 0x44(68)
        # Select configuation-1register, 0x01(01)
        # 0x0D(13) Operation: RGB, Range: 360 lux, Res: 16 Bits
        bus.write_byte_data(0x44, 0x01, 0x05)

            # function for turning
        def turn(min_left, min_right, turn_value):
            if min_right < min_left:
                twist.angular.z = turn_value  # left
                self._cmd_pub.publish(twist)
                #rospy.loginfo('Turn left!')
            else:  # min_distance_left < min_distance_right
                twist.angular.z = -turn_value  # right
                self._cmd_pub.publish(twist)
                #rospy.loginfo('Turn right!')

        # runtime loopet
        while time.time() < t_end:  # runs for X secs
            lidar_distances = self.get_scan()
            min_distance = min(lidar_distances)
            min_distance_right = min(lidar_distances[0:29])
            min_distance_center = min(lidar_distances[30:59])
            min_distance_left = min(lidar_distances[60:89])

            if min_distance_center < SAFE_STOP_DISTANCE:  # something need to be happen
                if min_distance_center > 0.35:  #range 2
                    rospy.loginfo('Between 50 and 35')
                    turn(min_distance_left, min_distance_right, 0.8)

                elif min_distance_center > 0.24:  # range 1
                    rospy.loginfo('Between 35 and 24')
                    turn(min_distance_left, min_distance_right, 1.6)
                else: # range 0
                    rospy.loginfo('Below 23')
                    twist.linear.x = 0  # stop
                    twist.angular.z = 4  # left
                    self._cmd_pub.publish(twist)
                    full_stop_turn_count = full_stop_turn_count + 1
                    # rospy.loginfo('Turn left!')
                    # turn(min_distance_left, min_distance_right, 3)
                    # time.sleep(3)

            else:
                twist.linear.x = LINEAR_VEL
                twist.angular.z = 0.0
                self._cmd_pub.publish(twist)
                turtlebot_moving = True
                # rospy.loginfo('Distance of the obstacle : %f',
                #               min_distance_center)

        # collision
        if min_distance_center <= 0.04 or min_distance_left <= 0.05 or min_distance_right <= 0.05:
            collision_count = collision_count + 1

       
        rospy.loginfo('collision count : %f', collision_count)
        rospy.loginfo('full stop turn count : %f', full_stop_turn_count)


def main():
    rospy.init_node('turtlebot3_obstacle')
    rospy.Subscriber('/odom', Odometry, odometryCallback)
    try:
        obstacle = Obstacle()
    except rospy.ROSInterruptException:
        pass


if __name__ == '__main__':
    main()
